// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApp.DataAccess.Context;

#nullable disable

namespace WebApp.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240111200738_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("WebApp.Domain.Entities.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("Department")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<DateTime?>("DoB")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<DateTime?>("HireDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("JoiningDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<float>("Salary")
                        .HasColumnType("REAL");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            Address = "",
                            Department = "X",
                            FirstName = "Aslam",
                            LastName = "Shaikh",
                            Salary = 100.9f
                        },
                        new
                        {
                            EmployeeId = 2,
                            Address = "",
                            Department = "B",
                            FirstName = "Abhijit",
                            LastName = "Idekar",
                            Salary = 300.9f
                        },
                        new
                        {
                            EmployeeId = 3,
                            Address = "",
                            Department = "P",
                            FirstName = "Maksud",
                            LastName = "Aditya",
                            Salary = 200.9f
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
